clean project1

diff --git a/project1/xtf b/project1/xtf
--- a/project1/xtf
+++ b/project1/xtf
@@ -121,13 +121,13 @@ set_argument() {
             if ! echo "$2" | grep -Eq "$REGEX_DATE"; then
                 echo "Wrong date format" >&2
                 exit 1
-            else
-                if ! date -d "$2" >/dev/null 2>&1; then
-                    if ! date -j -f "%Y-%m-%d %H:%M:%S" "$2" >/dev/null 2>&1; then
-                        echo "Invalid date $2" >&2
-                        exit 1
-                    fi
-                fi
+            # else
+            #     if ! date -d "$2" >/dev/null 2>&1; then
+            #         if ! date -j -f "%Y-%m-%d %H:%M:%S" "$2" >/dev/null 2>&1; then
+            #             echo "Invalid date $2" >&2
+            #             exit 1
+            #         fi
+            #     fi
             fi
         fi
 
@@ -150,14 +150,7 @@ file_format_check() {
         if (NF!=4 || !length($1) || !length($2) || !length($3) || !length($4) || ($4+0 != $4)) {
             print "File contains invalid data"; exit 1
         }
-        
-        split($2, dateTime, " ");
-        split(dateTime[1], dateParts, "-");
-        split(dateTime[2], timeParts, ":");
-        
-        timeStr = dateParts[1] " " dateParts[2] " " dateParts[3] " " timeParts[1] " " timeParts[2] " " timeParts[3];
-        
-        if (mktime(timeStr) == -1) {
+        if ($2 !~ /[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]/) {
             print "Invalid date"; exit 1
         }
     }')
@@ -239,10 +232,9 @@ while [ "$#" -gt 0 ]; do
                     exit 1
                 fi
 
+
             # CHECK HERE FILE VALIDITY
             file_format_check "$file"
-
-
             done
 
             if [ "$COMMAND" = "list" ]; then
